import type { CRMActivity, CRMDeal, CRMLead } from "./crm.types";

export const CRM_QA_LEADS: CRMLead[] = [
  {
    id: "LEAD-QA-001",
    storeName: "Mekong Brew Cafe",
    legalCompanyName: "Mekong Brew Sole Co., Ltd.",
    primaryContact: "Noy Kham",
    phone: "020 5555 1001",
    whatsapp: "020 5555 1001",
    province: "Vientiane Capital",
    source: "EVENT",
    campaign: "Lao Food Expo 2026",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    status: "FOLLOW_UP",
    nextActivity: "DEMO",
    nextActivityAt: "2026-09-11 14:00",
    note: "Interested in QSR + dynamic LAO QR.",
  },
  {
    id: "LEAD-QA-002",
    storeName: "Khampheng Restaurant",
    individualName: "Khampheng Phommasone",
    primaryContact: "Khampheng",
    phone: "020 5555 1002",
    province: "Vientiane Capital",
    source: "OWN_LEAD",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    status: "NEW",
  },
  {
    id: "LEAD-QA-003",
    storeName: "Pakse Riverside Hotel",
    legalCompanyName: "Riverside Hospitality Co., Ltd.",
    primaryContact: "Sengdao",
    phone: "020 5555 1003",
    email: "sales@qa-riverside.example",
    province: "Champasak",
    source: "REFERRAL",
    businessUnit: "QPOS",
    owner: "QA Sales B",
    status: "CONTACTED",
    nextActivity: "FOLLOW_UP",
    nextActivityAt: "2026-09-12 10:00",
  },
  {
    id: "LEAD-QA-004",
    storeName: "Petrotrade Integration QA",
    legalCompanyName: "Petrotrade QA Co., Ltd.",
    primaryContact: "QA Project Contact",
    phone: "020 5555 2001",
    province: "Vientiane Capital",
    source: "PARTNER",
    businessUnit: "IQURI_X",
    project: "Petrotrade",
    owner: "QA Sales X",
    status: "FOLLOW_UP",
    nextActivity: "MEETING",
    nextActivityAt: "2026-09-11 15:30",
  },
];

export const CRM_QA_ACTIVITIES: CRMActivity[] = [
  {
    id: "ACT-QA-001",
    type: "CALL",
    subject: "First contact",
    relatedName: "Khampheng Restaurant",
    relatedType: "LEAD",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    scheduledAt: "2026-09-11 09:30",
    status: "SCHEDULED",
    bucket: "TODAY",
  },
  {
    id: "ACT-QA-002",
    type: "DEMO",
    subject: "QPOS QSR demo",
    relatedName: "Mekong Brew Cafe",
    relatedType: "DEAL",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    scheduledAt: "2026-09-11 14:00",
    status: "SCHEDULED",
    bucket: "TODAY",
    note: "Show QSR, offline mode and dynamic LAO QR.",
  },
  {
    id: "ACT-QA-003",
    type: "FOLLOW_UP",
    subject: "Follow up after quotation",
    relatedName: "North Gate Coffee",
    relatedType: "DEAL",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    scheduledAt: "2026-09-10 16:00",
    status: "OVERDUE",
    bucket: "OVERDUE",
    quotationNumber: "QT-000248",
  },
  {
    id: "ACT-QA-004",
    type: "MEETING",
    subject: "Project scope meeting",
    relatedName: "Petrotrade Integration QA",
    relatedType: "DEAL",
    businessUnit: "IQURI_X",
    owner: "QA Sales X",
    scheduledAt: "2026-09-11 15:30",
    status: "SCHEDULED",
    bucket: "TODAY",
  },
];

export const CRM_QA_DEALS: CRMDeal[] = [
  {
    id: "DEAL-QA-001",
    storeName: "Khampheng Restaurant",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    stage: "NEW_DEAL",
    value: 6900000,
    currency: "LAK",
    nextActivity: "CALL",
    nextActivityAt: "2026-09-11 09:30",
  },
  {
    id: "DEAL-QA-002",
    storeName: "Mekong Brew Cafe",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    stage: "DEMO",
    value: 12900000,
    currency: "LAK",
    nextActivity: "DEMO",
    nextActivityAt: "2026-09-11 14:00",
    expectedCloseDate: "2026-09-18",
  },
  {
    id: "DEAL-QA-003",
    storeName: "North Gate Coffee",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    stage: "QUOTATION",
    value: 14900000,
    currency: "LAK",
    quotationNumber: "QT-000248",
    quotationConfirmed: false,
    nextActivity: "FOLLOW_UP",
    nextActivityAt: "2026-09-10 16:00",
  },
  {
    id: "DEAL-QA-004",
    storeName: "Pakse Riverside Hotel",
    businessUnit: "QPOS",
    owner: "QA Sales B",
    stage: "NEGOTIATION",
    value: 24000000,
    currency: "LAK",
    nextActivity: "FOLLOW_UP",
    nextActivityAt: "2026-09-12 10:00",
  },
  {
    id: "DEAL-QA-005",
    storeName: "Central Bistro",
    businessUnit: "QPOS",
    owner: "QA Sales B",
    stage: "CONTRACT",
    value: 9000000,
    currency: "LAK",
    quotationNumber: "QT-000244",
    quotationConfirmed: true,
    nextActivity: "CONTRACT",
    nextActivityAt: "2026-09-11 13:00",
  },
  {
    id: "DEAL-QA-006",
    storeName: "VTE Bakery",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    stage: "PAYMENT",
    value: 7900000,
    currency: "LAK",
    quotationNumber: "QT-000239",
    quotationConfirmed: true,
    paymentSlipUploaded: true,
  },
  {
    id: "DEAL-QA-007",
    storeName: "No Next Activity Cafe",
    businessUnit: "QPOS",
    owner: "QA Sales A",
    stage: "NEGOTIATION",
    value: 5000000,
    currency: "LAK",
  },
  {
    id: "DEAL-QA-008",
    storeName: "Petrotrade Integration QA",
    businessUnit: "IQURI_X",
    owner: "QA Sales X",
    stage: "DEMO",
    value: 85000,
    currency: "USD",
    nextActivity: "MEETING",
    nextActivityAt: "2026-09-11 15:30",
  },
];
