"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import QBMSAppShell, { QBMSIcon } from "@/components/layout/QBMSAppShell";
import { useSuperAdminLocale } from "@/super-admin/i18n/useSuperAdminLocale";
import { fetchAuditLogOverview, type AuditLogEntry, type AuditLogOverview } from "./audit-log.api";
import styles from "./AuditLogPage.module.css";

const copy={
  en:{pageTitle:"Audit Log",pageDescription:"Trace security-sensitive changes and administration activity across Q BMS.",search:"Search action, entity, Employee ID, name or email...",eyebrow:"SUPER ADMIN / GOVERNANCE",title:"Audit Log",intro:"Review who changed what, which entity was affected and when it happened. Metadata containing tokens, secrets or passwords is redacted by the Backend before delivery.",readOnly:"READ-ONLY",back:"← Super Admin",total:"Total Events",totalHelp:"All Audit records",today:"Today",todayHelp:"Events since 00:00 today",last24:"Last 24 Hours",last24Help:"Activity in the last 24 hours",actors:"Actors",actorsHelp:"Users that created Audit Events",allActions:"All Actions",allEntities:"All Entity Types",allActors:"All Actors",clear:"Clear",activity:"Activity",records:"records",time:"Time",actor:"Actor",action:"Action",entity:"Entity",loading:"Loading Audit Log...",noEvents:"No Audit Event matches this filter.",systemEvent:"System Event",noEntityId:"No Entity ID",page:"Page",of:"of",previous:"← Previous",next:"Next →",selectEvent:"Select an Audit Event",selectHelp:"to inspect details and Metadata",eventDetail:"EVENT DETAIL",system:"System",actionCode:"Action Code",auditEvent:"Audit Event",metadata:"SANITIZED METADATA",payload:"Event Payload",redacted:"Sensitive fields redacted",noMetadata:"No metadata",loadError:"Unable to load Audit Log."},
  th:{pageTitle:"บันทึกการตรวจสอบ",pageDescription:"ตรวจสอบการเปลี่ยนแปลงสำคัญด้านความปลอดภัยและกิจกรรมการบริหารใน Q BMS",search:"ค้นหา Action, Entity, Employee ID, ชื่อ หรืออีเมล...",eyebrow:"SUPER ADMIN / การกำกับดูแล",title:"บันทึกการตรวจสอบ",intro:"ตรวจสอบว่าใครทำอะไร กับข้อมูลไหน และเกิดขึ้นเมื่อไหร่ โดย Metadata ที่อาจมี Token / Secret / Password จะถูก Redact จาก Backend ก่อนส่งออกมา",readOnly:"อ่านอย่างเดียว",back:"← Super Admin",total:"Event ทั้งหมด",totalHelp:"Audit Record ทั้งหมด",today:"วันนี้",todayHelp:"Event ตั้งแต่ 00:00 วันนี้",last24:"24 ชั่วโมงล่าสุด",last24Help:"Activity ใน 24 ชั่วโมงล่าสุด",actors:"ผู้ดำเนินการ",actorsHelp:"User ที่เคยสร้าง Audit Event",allActions:"ทุก Action",allEntities:"ทุก Entity Type",allActors:"ทุก Actor",clear:"ล้างตัวกรอง",activity:"Activity",records:"รายการ",time:"เวลา",actor:"ผู้ดำเนินการ",action:"Action",entity:"Entity",loading:"กำลังโหลด Audit Log...",noEvents:"ไม่พบ Audit Event ตามตัวกรอง",systemEvent:"System Event",noEntityId:"ไม่มี Entity ID",page:"หน้า",of:"จาก",previous:"← ก่อนหน้า",next:"ถัดไป →",selectEvent:"เลือก Audit Event",selectHelp:"เพื่อดูรายละเอียดและ Metadata",eventDetail:"รายละเอียด EVENT",system:"System",actionCode:"Action Code",auditEvent:"Audit Event",metadata:"METADATA ที่ผ่านการ SANITIZE",payload:"Event Payload",redacted:"ซ่อนข้อมูล Sensitive แล้ว",noMetadata:"ไม่มี Metadata",loadError:"ไม่สามารถโหลด Audit Log ได้"},
  lo:{pageTitle:"ບັນທຶກການກວດສອບ",pageDescription:"ກວດສອບການປ່ຽນແປງສຳຄັນດ້ານຄວາມປອດໄພ ແລະ ກິດຈະກຳການບໍລິຫານໃນ Q BMS",search:"ຄົ້ນຫາ Action, Entity, Employee ID, ຊື່ ຫຼື ອີເມວ...",eyebrow:"SUPER ADMIN / ການກຳກັບດູແລ",title:"ບັນທຶກການກວດສອບ",intro:"ກວດສອບວ່າໃຜເຮັດຫຍັງ, ກັບຂໍ້ມູນໃດ ແລະ ເກີດຂຶ້ນເມື່ອໃດ. Metadata ທີ່ອາດມີ Token / Secret / Password ຈະຖືກ Redact ຈາກ Backend ກ່ອນສົ່ງ",readOnly:"ອ່ານຢ່າງດຽວ",back:"← Super Admin",total:"Event ທັງໝົດ",totalHelp:"Audit Record ທັງໝົດ",today:"ມື້ນີ້",todayHelp:"Event ຕັ້ງແຕ່ 00:00 ມື້ນີ້",last24:"24 ຊົ່ວໂມງຫຼ້າສຸດ",last24Help:"Activity ໃນ 24 ຊົ່ວໂມງຫຼ້າສຸດ",actors:"ຜູ້ດຳເນີນການ",actorsHelp:"User ທີ່ເຄີຍສ້າງ Audit Event",allActions:"ທຸກ Action",allEntities:"ທຸກ Entity Type",allActors:"ທຸກ Actor",clear:"ລ້າງຕົວກອງ",activity:"Activity",records:"ລາຍການ",time:"ເວລາ",actor:"ຜູ້ດຳເນີນການ",action:"Action",entity:"Entity",loading:"ກຳລັງໂຫຼດ Audit Log...",noEvents:"ບໍ່ພົບ Audit Event ຕາມຕົວກອງ",systemEvent:"System Event",noEntityId:"ບໍ່ມີ Entity ID",page:"ໜ້າ",of:"ຈາກ",previous:"← ກ່ອນໜ້າ",next:"ຕໍ່ໄປ →",selectEvent:"ເລືອກ Audit Event",selectHelp:"ເພື່ອເບິ່ງລາຍລະອຽດ ແລະ Metadata",eventDetail:"ລາຍລະອຽດ EVENT",system:"System",actionCode:"Action Code",auditEvent:"Audit Event",metadata:"METADATA ທີ່ຜ່ານການ SANITIZE",payload:"Event Payload",redacted:"ປິດບັງຂໍ້ມູນ Sensitive ແລ້ວ",noMetadata:"ບໍ່ມີ Metadata",loadError:"ບໍ່ສາມາດໂຫຼດ Audit Log ໄດ້"}
} as const;

function formatDate(value:string|null,locale:"en"|"lo"|"th"){if(!value)return"—";const date=new Date(value);if(Number.isNaN(date.getTime()))return"—";const language=locale==="th"?"th-TH":locale==="lo"?"lo-LA":"en-GB";return new Intl.DateTimeFormat(language,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(date);}
function actionLabel(action:string){return action.replace(/[._-]+/g," ").replace(/\b\w/g,char=>char.toUpperCase());}
function actionTone(action:string){const n=action.toUpperCase();if(n.includes("DELETE")||n.includes("REVOKE")||n.includes("REMOVE")||n.includes("SUSPEND"))return styles.actionDanger;if(n.includes("CREATE")||n.includes("ACTIVAT")||n.includes("APPROVE")||n.includes("COMPLETE")||n.includes("ASSIGN"))return styles.actionPositive;return styles.actionNeutral;}

export default function AuditLogPageClient(){
  const locale=useSuperAdminLocale();const c=copy[locale];const [overview,setOverview]=useState<AuditLogOverview|null>(null);const [selected,setSelected]=useState<AuditLogEntry|null>(null);const [searchInput,setSearchInput]=useState("");const [query,setQuery]=useState("");const [action,setAction]=useState("");const [entityType,setEntityType]=useState("");const [actorUserId,setActorUserId]=useState("");const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  function stringifyMetadata(metadata:unknown){if(metadata===null||metadata===undefined)return c.noMetadata;if(typeof metadata==="string")return metadata;try{return JSON.stringify(metadata,null,2);}catch{return String(metadata);}}
  useEffect(()=>{const timer=window.setTimeout(()=>{setQuery(searchInput.trim());setPage(1);},300);return()=>window.clearTimeout(timer);},[searchInput]);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);fetchAuditLogOverview({q:query,action,entityType,actorUserId,page,pageSize:50},controller.signal).then(data=>{setOverview(data);setSelected(cur=>cur&&data.logs.some(item=>item.id===cur.id)?cur:data.logs[0]||null);}).catch(e=>{if(controller.signal.aborted)return;setError(e instanceof Error?e.message:c.loadError);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[query,action,entityType,actorUserId,page]);
  const filterCount=useMemo(()=>[action,entityType,actorUserId].filter(Boolean).length,[action,entityType,actorUserId]);function clearFilters(){setAction("");setEntityType("");setActorUserId("");setSearchInput("");setQuery("");setPage(1);}
  return <QBMSAppShell pageTitle={c.pageTitle} pageDescription={c.pageDescription} searchValue={searchInput} onSearchChange={setSearchInput} searchPlaceholder={c.search}><div className={styles.page}>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{c.eyebrow}</span><h2>{c.title}</h2><p>{c.intro}</p></div><div className={styles.heroRight}><span className={styles.readOnly}><QBMSIcon name="shield" size={16}/>{c.readOnly}</span><Link href="/super-admin" className={styles.backLink}>{c.back}</Link></div></section>{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.metrics}><article><span>{c.total}</span><strong>{overview?.counts.total??"—"}</strong><small>{c.totalHelp}</small></article><article><span>{c.today}</span><strong>{overview?.counts.today??"—"}</strong><small>{c.todayHelp}</small></article><article><span>{c.last24}</span><strong>{overview?.counts.last24Hours??"—"}</strong><small>{c.last24Help}</small></article><article><span>{c.actors}</span><strong>{overview?.counts.uniqueActors??"—"}</strong><small>{c.actorsHelp}</small></article></section>
    <section className={styles.filterBar}><select value={action} onChange={e=>{setAction(e.target.value);setPage(1);}}><option value="">{c.allActions}</option>{(overview?.filters.actions||[]).map(item=><option key={item.value} value={item.value}>{actionLabel(item.value)} ({item.count})</option>)}</select><select value={entityType} onChange={e=>{setEntityType(e.target.value);setPage(1);}}><option value="">{c.allEntities}</option>{(overview?.filters.entityTypes||[]).map(item=><option key={item.value} value={item.value}>{item.value} ({item.count})</option>)}</select><select value={actorUserId} onChange={e=>{setActorUserId(e.target.value);setPage(1);}}><option value="">{c.allActors}</option>{(overview?.filters.actors||[]).map(item=><option key={item.userId} value={item.userId}>{item.displayName}{item.employeeCode?` · ${item.employeeCode}`:""}</option>)}</select><button type="button" className={styles.clearButton} disabled={!filterCount&&!searchInput} onClick={clearFilters}>{c.clear} {filterCount?`(${filterCount})`:""}</button></section>
    <section className={styles.workspace}><div className={styles.tablePanel}><div className={styles.tableHead}><div><span className={styles.kicker}>AUDIT EVENTS</span><h3>{c.activity}</h3></div><span className={styles.resultCount}>{overview?.pagination.total??0} {c.records}</span></div><div className={styles.table}><div className={`${styles.row} ${styles.headerRow}`}><span>{c.time}</span><span>{c.actor}</span><span>{c.action}</span><span>{c.entity}</span></div>{loading&&<div className={styles.empty}>{c.loading}</div>}{!loading&&!(overview?.logs.length)&&<div className={styles.empty}>{c.noEvents}</div>}{(overview?.logs||[]).map(entry=><button key={entry.id} type="button" className={`${styles.row} ${styles.dataRow} ${selected?.id===entry.id?styles.selectedRow:""}`} onClick={()=>setSelected(entry)}><span className={styles.timeCell}><strong>{formatDate(entry.createdAt,locale)}</strong><small>#{entry.id}</small></span><span className={styles.actorCell}><strong>{entry.actor.displayName}</strong><small>{[entry.actor.employeeCode,entry.actor.email].filter(Boolean).join(" · ")||c.systemEvent}</small></span><span><b className={`${styles.actionBadge} ${actionTone(entry.action)}`}>{actionLabel(entry.action)}</b><small className={styles.rawAction}>{entry.action}</small></span><span className={styles.entityCell}><strong>{entry.entityType||"—"}</strong><small>{entry.entityId||c.noEntityId}</small></span></button>)}</div><div className={styles.pagination}><span>{c.page} {overview?.pagination.page??1} {c.of} {overview?.pagination.pageCount??1}</span><div><button type="button" disabled={!overview?.pagination.hasPrevious||loading} onClick={()=>setPage(cur=>Math.max(1,cur-1))}>{c.previous}</button><button type="button" disabled={!overview?.pagination.hasNext||loading} onClick={()=>setPage(cur=>cur+1)}>{c.next}</button></div></div></div>
      <aside className={styles.detailPanel}>{!selected?<div className={styles.emptyDetail}><QBMSIcon name="report" size={28}/><strong>{c.selectEvent}</strong><span>{c.selectHelp}</span></div>:<><div className={styles.detailHead}><span className={styles.kicker}>{c.eventDetail}</span><h3>{actionLabel(selected.action)}</h3><p>{formatDate(selected.createdAt,locale)}</p></div><div className={styles.detailGrid}><div><span>{c.actor}</span><strong>{selected.actor.displayName}</strong><small>{[selected.actor.employeeCode,selected.actor.email].filter(Boolean).join(" · ")||c.system}</small></div><div><span>{c.entity}</span><strong>{selected.entityType||"—"}</strong><small>{selected.entityId||c.noEntityId}</small></div><div><span>{c.actionCode}</span><strong>{selected.action}</strong><small>{c.auditEvent} #{selected.id}</small></div></div><section className={styles.metadataSection}><div className={styles.metadataHead}><div><span className={styles.kicker}>{c.metadata}</span><h3>{c.payload}</h3></div><span className={styles.redactedBadge}>{c.redacted}</span></div><pre>{stringifyMetadata(selected.metadata)}</pre></section></>}</aside>
    </section>
  </div></QBMSAppShell>;
}
