"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import QBMSAppShell, { QBMSIcon } from "@/components/layout/QBMSAppShell";
import { useSuperAdminLocale } from "@/super-admin/i18n/useSuperAdminLocale";
import {
  fetchAccessControlOverview,
  fetchOrganizationPermissionPolicy,
  fetchUserEffectivePermissionPreview,
  simulateEffectivePermissionPreview,
  type AccessControlOverview,
  type EffectivePermissionEvaluation,
  type OrganizationPermissionPolicy,
  type UserEffectivePermissionPreview,
} from "./access-control.api";
import styles from "./EffectivePermissionPreviewPage.module.css";

type Mode = "ACTUAL" | "SIMULATION";

const copy = {
  en:{pageTitle:"Effective Permission Preview",pageDescription:"Inspect an Employee's real permissions or simulate Role / Level / Grade in read-only mode.",search:"Search Permission, Group or Role...",eyebrow:"ROLES & PERMISSIONS / EFFECTIVE ACCESS",title:"Preview As / Effective Permission",intro:"Safe read-only preview. It never changes a real user's Role, Level, Grade or Permission.",rule1:"Role = additive",rule2:"Grade overrides Level",rule3:"No writes",back:"← Roles & Permissions",actualUser:"Actual User",simulation:"Simulation",qbmsUser:"Q BMS User",noUser:"No Q BMS User",employee:"Employee",noEmployeeCode:"No Employee Code",unknown:"Unknown",organization:"Organization",noPosition:"No Active Position",grade:"Grade",noOrg:"No active organization assignment",jobLevel:"Job Level",jobGrade:"Job Grade",calculating:"Calculating...",runPreview:"Run Preview",base:"Base",effective:"Effective",effectiveHelp:"Permissions available in the final result",fromRole:"From Role",fromRoleHelp:"Base / Admin / System Role",fromOrg:"From Organization",fromOrgHelp:"Level after Grade Override",gradeOverrides:"Grade Overrides",gradeOverridesHelp:"Grade Grant / Revoke rules",breakdown:"Permission Breakdown",effectiveOnly:"Effective only",permission:"Permission",role:"Role",level:"Level",yes:"YES",no:"NO",inherit:"INHERIT",noSource:"No source",roleSource:"Role",gradeGrant:"Grade: GRANT",gradeRevoke:"Grade: REVOKE",levelGrant:"Level: GRANT",calculatingPermissions:"Calculating Effective Permission...",simulationPrompt:"Select Role / Level / Grade and run Preview",actualPrompt:"Select a Q BMS User to inspect effective permissions",readOnlyNote:"This page is read-only and never changes real data.",loadError:"Unable to load permission preview.",userPreviewError:"Unable to preview user permissions.",simulationError:"Unable to simulate permissions."},
  th:{pageTitle:"ตรวจสอบ Effective Permission",pageDescription:"ตรวจสิทธิ์จริงของ Employee หรือจำลอง Role / Level / Grade แบบอ่านอย่างเดียว",search:"ค้นหา Permission, Group หรือ Role...",eyebrow:"บทบาทและสิทธิ์ / EFFECTIVE ACCESS",title:"Preview As / Effective Permission",intro:"เป็น Safe Read-only Preview ไม่มีการเปลี่ยน Role, Level, Grade หรือ Permission ของผู้ใช้งานจริง",rule1:"Role = Additive",rule2:"Grade Override Level",rule3:"ไม่มีการเขียนข้อมูล",back:"← บทบาทและสิทธิ์",actualUser:"ผู้ใช้จริง",simulation:"จำลอง",qbmsUser:"Q BMS User",noUser:"ยังไม่มี Q BMS User",employee:"Employee",noEmployeeCode:"ยังไม่มี Employee Code",unknown:"ไม่ทราบสถานะ",organization:"Organization",noPosition:"ยังไม่มี Active Position",grade:"Grade",noOrg:"ยังไม่มี Active Organization Assignment",jobLevel:"Job Level",jobGrade:"Job Grade",calculating:"กำลังคำนวณ...",runPreview:"รัน Preview",base:"Base",effective:"สิทธิ์ที่มีผลจริง",effectiveHelp:"Permission ที่ใช้งานได้ในผลลัพธ์สุดท้าย",fromRole:"มาจาก Role",fromRoleHelp:"Base / Admin / System Role",fromOrg:"มาจาก Organization",fromOrgHelp:"Level หลัง Grade Override",gradeOverrides:"Grade Override",gradeOverridesHelp:"กฎ Grant / Revoke ของ Grade",breakdown:"รายละเอียด Permission",effectiveOnly:"เฉพาะ Effective",permission:"Permission",role:"Role",level:"Level",yes:"ใช่",no:"ไม่",inherit:"รับช่วง",noSource:"ไม่มี Source",roleSource:"Role",gradeGrant:"Grade: GRANT",gradeRevoke:"Grade: REVOKE",levelGrant:"Level: GRANT",calculatingPermissions:"กำลังคำนวณ Effective Permission...",simulationPrompt:"เลือก Role / Level / Grade แล้วกด Run Preview",actualPrompt:"เลือก Q BMS User เพื่อดูสิทธิ์จริง",readOnlyNote:"หน้านี้เป็น Read-only และไม่แก้ข้อมูลจริง",loadError:"ไม่สามารถโหลด Permission Preview ได้",userPreviewError:"ไม่สามารถดู Permission ของ User ได้",simulationError:"ไม่สามารถจำลอง Permission ได้"},
  lo:{pageTitle:"ກວດສອບ Effective Permission",pageDescription:"ກວດສິດຈິງຂອງ Employee ຫຼື ຈຳລອງ Role / Level / Grade ແບບອ່ານຢ່າງດຽວ",search:"ຄົ້ນຫາ Permission, Group ຫຼື Role...",eyebrow:"ບົດບາດ ແລະ ສິດທິ / EFFECTIVE ACCESS",title:"Preview As / Effective Permission",intro:"Safe Read-only Preview ທີ່ບໍ່ປ່ຽນ Role, Level, Grade ຫຼື Permission ຂອງຜູ້ໃຊ້ຈິງ",rule1:"Role = Additive",rule2:"Grade Override Level",rule3:"ບໍ່ຂຽນຂໍ້ມູນ",back:"← ບົດບາດ ແລະ ສິດທິ",actualUser:"ຜູ້ໃຊ້ຈິງ",simulation:"ຈຳລອງ",qbmsUser:"Q BMS User",noUser:"ຍັງບໍ່ມີ Q BMS User",employee:"Employee",noEmployeeCode:"ຍັງບໍ່ມີ Employee Code",unknown:"ບໍ່ຮູ້ສະຖານະ",organization:"Organization",noPosition:"ຍັງບໍ່ມີ Active Position",grade:"Grade",noOrg:"ຍັງບໍ່ມີ Active Organization Assignment",jobLevel:"Job Level",jobGrade:"Job Grade",calculating:"ກຳລັງຄຳນວນ...",runPreview:"Run Preview",base:"Base",effective:"ສິດທີ່ມີຜົນຈິງ",effectiveHelp:"Permission ທີ່ໃຊ້ງານໄດ້ໃນຜົນສຸດທ້າຍ",fromRole:"ມາຈາກ Role",fromRoleHelp:"Base / Admin / System Role",fromOrg:"ມາຈາກ Organization",fromOrgHelp:"Level ຫຼັງ Grade Override",gradeOverrides:"Grade Override",gradeOverridesHelp:"ກົດ Grant / Revoke ຂອງ Grade",breakdown:"ລາຍລະອຽດ Permission",effectiveOnly:"ສະເພາະ Effective",permission:"Permission",role:"Role",level:"Level",yes:"ແມ່ນ",no:"ບໍ່",inherit:"ຮັບຊ່ວງ",noSource:"ບໍ່ມີ Source",roleSource:"Role",gradeGrant:"Grade: GRANT",gradeRevoke:"Grade: REVOKE",levelGrant:"Level: GRANT",calculatingPermissions:"ກຳລັງຄຳນວນ Effective Permission...",simulationPrompt:"ເລືອກ Role / Level / Grade ແລ້ວ Run Preview",actualPrompt:"ເລືອກ Q BMS User ເພື່ອເບິ່ງສິດຈິງ",readOnlyNote:"ໜ້ານີ້ເປັນ Read-only ແລະ ບໍ່ແກ້ຂໍ້ມູນຈິງ",loadError:"ບໍ່ສາມາດໂຫຼດ Permission Preview ໄດ້",userPreviewError:"ບໍ່ສາມາດເບິ່ງ Permission ຂອງ User ໄດ້",simulationError:"ບໍ່ສາມາດຈຳລອງ Permission ໄດ້"}
} as const;

export default function EffectivePermissionPreviewPageClient(){
  const locale=useSuperAdminLocale();const c=copy[locale];const [mode,setMode]=useState<Mode>("ACTUAL");const [overview,setOverview]=useState<AccessControlOverview|null>(null);const [policy,setPolicy]=useState<OrganizationPermissionPolicy|null>(null);const [selectedUserId,setSelectedUserId]=useState("");const [actualPreview,setActualPreview]=useState<UserEffectivePermissionPreview|null>(null);const [simulationRoleCodes,setSimulationRoleCodes]=useState<string[]>(["EMPLOYEE"]);const [simulationLevelId,setSimulationLevelId]=useState("");const [simulationGradeId,setSimulationGradeId]=useState("");const [simulationEvaluation,setSimulationEvaluation]=useState<EffectivePermissionEvaluation|null>(null);const [permissionQuery,setPermissionQuery]=useState("");const [effectiveOnly,setEffectiveOnly]=useState(false);const [loading,setLoading]=useState(true);const [previewLoading,setPreviewLoading]=useState(false);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{const controller=new AbortController();Promise.all([fetchAccessControlOverview(controller.signal),fetchOrganizationPermissionPolicy(controller.signal)]).then(([o,p])=>{setOverview(o);setPolicy(p);setSelectedUserId(o.users[0]?.id||"");setSimulationLevelId(p.levels[0]?.id||"");}).catch(e=>{if(controller.signal.aborted)return;setError(e instanceof Error?e.message:c.loadError);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
  const grades=useMemo(()=>(policy?.grades||[]).filter(g=>g.jobLevelId===simulationLevelId),[policy,simulationLevelId]);
  useEffect(()=>{setSimulationGradeId(cur=>grades.some(g=>g.id===cur)?cur:grades[0]?.id||"");},[grades]);
  useEffect(()=>{if(mode!=="ACTUAL"||!selectedUserId){setActualPreview(null);return;}const controller=new AbortController();setPreviewLoading(true);setError(null);fetchUserEffectivePermissionPreview(selectedUserId,controller.signal).then(setActualPreview).catch(e=>{if(controller.signal.aborted)return;setError(e instanceof Error?e.message:c.userPreviewError);}).finally(()=>{if(!controller.signal.aborted)setPreviewLoading(false);});return()=>controller.abort();},[mode,selectedUserId]);
  async function runSimulation(){setPreviewLoading(true);setError(null);try{const result=await simulateEffectivePermissionPreview(simulationRoleCodes,simulationLevelId||null,simulationGradeId||null);setSimulationEvaluation(result.evaluation);}catch(e){setError(e instanceof Error?e.message:c.simulationError);}finally{setPreviewLoading(false);}}
  const evaluation=mode==="ACTUAL"?actualPreview?.evaluation||null:simulationEvaluation;
  const filtered=useMemo(()=>{if(!evaluation)return[];const n=permissionQuery.trim().toLowerCase();return evaluation.permissions.filter(p=>{if(effectiveOnly&&!p.effective)return false;if(!n)return true;return[p.code,p.name,p.group,...p.roleCodes].join(" ").toLowerCase().includes(n);});},[evaluation,permissionQuery,effectiveOnly]);
  function toggleRole(code:string){if(code==="EMPLOYEE")return;setSimulationRoleCodes(cur=>cur.includes(code)?cur.filter(x=>x!==code):[...cur,code]);setSimulationEvaluation(null);}
  function sourceLabel(item:{roleGranted:boolean;roleCodes:string[];levelGranted:boolean;gradeEffect:string;organizationGranted:boolean}){const labels:string[]=[];if(item.roleGranted)labels.push(`${c.roleSource}: ${item.roleCodes.join(", ")}`);if(item.gradeEffect==="GRANT")labels.push(c.gradeGrant);else if(item.gradeEffect==="REVOKE")labels.push(c.gradeRevoke);else if(item.levelGranted)labels.push(c.levelGrant);return labels.length?labels.join(" · "):c.noSource;}
  return <QBMSAppShell pageTitle={c.pageTitle} pageDescription={c.pageDescription} searchValue={permissionQuery} onSearchChange={setPermissionQuery} searchPlaceholder={c.search}><div className={styles.page}>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{c.eyebrow}</span><h2>{c.title}</h2><p>{c.intro}</p></div><div className={styles.heroRight}><div className={styles.rulePills}><span>{c.rule1}</span><span>{c.rule2}</span><span>{c.rule3}</span></div><Link href="/super-admin/roles-permissions" className={styles.backLink}>{c.back}</Link></div></section>{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.modeCard}><div className={styles.modeSwitch}><button type="button" className={mode==="ACTUAL"?styles.activeMode:""} onClick={()=>setMode("ACTUAL")}>{c.actualUser}</button><button type="button" className={mode==="SIMULATION"?styles.activeMode:""} onClick={()=>setMode("SIMULATION")}>{c.simulation}</button></div>
      {mode==="ACTUAL"?<div className={styles.actualSelector}><label>{c.qbmsUser}<select value={selectedUserId} onChange={e=>setSelectedUserId(e.target.value)} disabled={loading||!overview?.users.length}>{!overview?.users.length&&<option value="">{c.noUser}</option>}{(overview?.users||[]).map(u=><option key={u.id} value={u.id}>{u.displayName}{u.employeeCode?` — ${u.employeeCode}`:""}</option>)}</select></label>{actualPreview&&<div className={styles.identitySummary}><div><span>{c.employee}</span><strong>{actualPreview.user.displayName}</strong><small>{actualPreview.user.employeeCode||c.noEmployeeCode}{" · "}{actualPreview.user.accountStatus||c.unknown}</small></div><div><span>{c.organization}</span><strong>{actualPreview.organization.positionName||c.noPosition}</strong><small>{[actualPreview.organization.businessUnitName,actualPreview.organization.jobLevelCode,actualPreview.organization.gradeNumber?`${c.grade} ${actualPreview.organization.gradeNumber}`:null].filter(Boolean).join(" · ")||c.noOrg}</small></div></div>}</div>
      :<div className={styles.simulationArea}><div className={styles.simulationInputs}><label>{c.jobLevel}<select value={simulationLevelId} onChange={e=>{setSimulationLevelId(e.target.value);setSimulationEvaluation(null);}}>{(policy?.levels||[]).map(level=><option key={level.id} value={level.id}>{level.code} — {level.name}</option>)}</select></label><label>{c.jobGrade}<select value={simulationGradeId} onChange={e=>{setSimulationGradeId(e.target.value);setSimulationEvaluation(null);}}>{grades.map(g=><option key={g.id} value={g.id}>{c.grade} {g.gradeNumber} — {g.name}</option>)}</select></label><button type="button" className={styles.runButton} onClick={runSimulation} disabled={previewLoading}>{previewLoading?c.calculating:c.runPreview}</button></div><div className={styles.roleChooser}>{(overview?.roles||[]).filter(r=>r.isAssignable).map(r=>{const checked=simulationRoleCodes.includes(r.code);const locked=r.code==="EMPLOYEE";return <button type="button" key={r.code} className={`${styles.roleChip} ${checked?styles.roleChipActive:""}`} onClick={()=>toggleRole(r.code)} disabled={locked}>{checked&&<QBMSIcon name="check" size={13}/>} {r.name} {locked&&<small>{c.base}</small>}</button>})}</div></div>}
    </section>
    {evaluation?<><section className={styles.metrics}><article><span>{c.effective}</span><strong>{evaluation.counts.effective}</strong><small>{c.effectiveHelp}</small></article><article><span>{c.fromRole}</span><strong>{evaluation.counts.roleGranted}</strong><small>{c.fromRoleHelp}</small></article><article><span>{c.fromOrg}</span><strong>{evaluation.counts.organizationGranted}</strong><small>{c.fromOrgHelp}</small></article><article><span>{c.gradeOverrides}</span><strong>{evaluation.counts.gradeOverrides}</strong><small>{c.gradeOverridesHelp}</small></article></section>
      <section className={styles.tableCard}><div className={styles.tableHead}><div><span className={styles.kicker}>EFFECTIVE ACCESS</span><h3>{c.breakdown}</h3></div><label className={styles.filterToggle}><input type="checkbox" checked={effectiveOnly} onChange={e=>setEffectiveOnly(e.target.checked)}/>{c.effectiveOnly}</label></div><div className={styles.permissionTable}><div className={`${styles.permissionRow} ${styles.headerRow}`}><span>{c.permission}</span><span>{c.role}</span><span>{c.level}</span><span>{c.grade}</span><span>{c.effective}</span></div>{filtered.map(p=><div key={p.code} className={styles.permissionRow}><span className={styles.permissionName}><strong>{p.name}</strong><small>{p.code}</small><em>{p.group}</em></span><span>{p.roleGranted?<b className={styles.grantBadge}>{p.roleCodes.join(", ")}</b>:<i>—</i>}</span><span>{p.levelGranted?<b className={styles.grantBadge}>GRANT</b>:<i>—</i>}</span><span>{p.gradeEffect==="GRANT"?<b className={styles.grantBadge}>GRANT</b>:p.gradeEffect==="REVOKE"?<b className={styles.revokeBadge}>REVOKE</b>:<i>{c.inherit}</i>}</span><span><b className={p.effective?styles.effectiveYes:styles.effectiveNo}>{p.effective?c.yes:c.no}</b><small className={styles.sourceText}>{sourceLabel(p)}</small></span></div>)}</div></section></>
    :<section className={styles.empty}>{previewLoading?<><QBMSIcon name="refresh" size={26}/><strong>{c.calculatingPermissions}</strong></>:<><QBMSIcon name="shield" size={28}/><strong>{mode==="SIMULATION"?c.simulationPrompt:c.actualPrompt}</strong><span>{c.readOnlyNote}</span></>}</section>}
  </div></QBMSAppShell>;
}
