"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import QBMSAppShell, { QBMSIcon } from "@/components/layout/QBMSAppShell";
import { useSuperAdminLocale } from "@/super-admin/i18n/useSuperAdminLocale";
import {
  fetchOrganizationPermissionPolicy,
  updateJobGradePermissionPolicy,
  updateJobLevelPermissionPolicy,
  type JobGradePermissionOverride,
  type OrganizationPermissionPolicy,
} from "./access-control.api";
import styles from "./OrganizationPermissionPolicyPage.module.css";

type GradeEffect = "INHERIT" | "GRANT" | "REVOKE";

const copy = {
  en:{pageTitle:"Level / Grade Permission Policy",pageDescription:"Define Employee capability by Job Level and allow Job Grade to override Level.",eyebrow:"ROLES & PERMISSIONS / ORGANIZATION POLICY",title:"Organization Permission Policy",intro:"Role Permissions are additive. Level provides Employee defaults, while Grade can Grant or Revoke the Level value for the same Permission.",rule1:"Role + Organization Policy",rule2:"Grade overrides Level",rule3:"Role cannot be revoked by Grade",back:"← Roles & Permissions",jobLevel:"Job Level",jobGrade:"Job Grade",grade:"Grade",policyPermissions:"Policy Permissions",levelDefault:"LEVEL DEFAULT",levelFallback:"Job Level",levelHelp:"Permissions enabled here become the default for every Grade under this Level.",saveLevel:"Save Level",saving:"Saving...",gradeOverride:"GRADE OVERRIDE",gradeFallback:"Job Grade",gradeHelp:"Inherit uses the Level value, Grant adds access, and Revoke removes access provided by Level.",saveGrade:"Save Grade",inherit:"Inherit",grant:"Grant",revoke:"Revoke",grantedByGrade:"GRANTED BY GRADE",revokedByGrade:"REVOKED BY GRADE",grantedByLevel:"GRANTED BY LEVEL",notGranted:"NOT GRANTED BY POLICY",baseRole:"EMPLOYEE Base Role",baseRoleHelp:"Base permissions available to employees",levelStep:"Level Default",levelStepHelp:"Additional capability by Job Level",gradeStep:"Grade Override",gradeStepHelp:"Grade changes only Permissions that need to differ",adminRole:"Admin Role",adminRoleHelp:"Additional Tool/Admin access independent from Grade",levelSaved:"Level default permissions saved.",gradeSaved:"Grade override saved.",loadError:"Unable to load Level / Grade permission policy.",levelSaveError:"Unable to save Job Level permission policy.",gradeSaveError:"Unable to save Job Grade permission policy."},
  th:{pageTitle:"นโยบาย Permission ตาม Level / Grade",pageDescription:"กำหนด Employee Capability ตาม Job Level และให้ Job Grade Override Level ได้",eyebrow:"บทบาทและสิทธิ์ / ORGANIZATION POLICY",title:"นโยบาย Permission ขององค์กร",intro:"Role Permission เป็นสิทธิ์แบบ Additive ส่วน Level เป็น Default ของ Employee และ Grade สามารถ Grant หรือ Revoke ค่า Level สำหรับ Permission เดียวกัน",rule1:"Role + Organization Policy",rule2:"Grade Override Level",rule3:"Grade ไม่สามารถ Revoke Role ได้",back:"← บทบาทและสิทธิ์",jobLevel:"Job Level",jobGrade:"Job Grade",grade:"Grade",policyPermissions:"Permission ใน Policy",levelDefault:"ค่าเริ่มต้นของ LEVEL",levelFallback:"Job Level",levelHelp:"Permission ที่เปิดตรงนี้จะเป็นค่า Default ของทุก Grade ภายใต้ Level นี้",saveLevel:"บันทึก Level",saving:"กำลังบันทึก...",gradeOverride:"GRADE OVERRIDE",gradeFallback:"Job Grade",gradeHelp:"Inherit ใช้ค่าจาก Level, Grant เพิ่มสิทธิ์ และ Revoke เอาสิทธิ์ที่ Level ให้ไว้ออก",saveGrade:"บันทึก Grade",inherit:"รับช่วง",grant:"ให้สิทธิ์",revoke:"ถอนสิทธิ์",grantedByGrade:"GRANT โดย GRADE",revokedByGrade:"REVOKE โดย GRADE",grantedByLevel:"GRANT โดย LEVEL",notGranted:"ไม่ได้รับจาก POLICY",baseRole:"EMPLOYEE Base Role",baseRoleHelp:"สิทธิ์พื้นฐานที่พนักงานมี",levelStep:"Level Default",levelStepHelp:"Capability เพิ่มเติมตาม Job Level",gradeStep:"Grade Override",gradeStepHelp:"Grade ปรับเฉพาะ Permission ที่ต้องแตกต่าง",adminRole:"Admin Role",adminRoleHelp:"สิทธิ์ Tool/Admin เพิ่มเติม ไม่ผูกกับ Grade",levelSaved:"บันทึก Default Permission ของ Level แล้ว",gradeSaved:"บันทึก Grade Override แล้ว",loadError:"ไม่สามารถโหลด Level / Grade Permission Policy ได้",levelSaveError:"ไม่สามารถบันทึก Job Level Permission Policy ได้",gradeSaveError:"ไม่สามารถบันทึก Job Grade Permission Policy ได้"},
  lo:{pageTitle:"ນະໂຍບາຍ Permission ຕາມ Level / Grade",pageDescription:"ກຳນົດ Employee Capability ຕາມ Job Level ແລະ ໃຫ້ Job Grade Override Level ໄດ້",eyebrow:"ບົດບາດ ແລະ ສິດທິ / ORGANIZATION POLICY",title:"ນະໂຍບາຍ Permission ຂອງອົງກອນ",intro:"Role Permission ເປັນສິດແບບ Additive; Level ເປັນ Default ຂອງ Employee ແລະ Grade ສາມາດ Grant ຫຼື Revoke ຄ່າ Level ໄດ້",rule1:"Role + Organization Policy",rule2:"Grade Override Level",rule3:"Grade ບໍ່ສາມາດ Revoke Role",back:"← ບົດບາດ ແລະ ສິດທິ",jobLevel:"Job Level",jobGrade:"Job Grade",grade:"Grade",policyPermissions:"Permission ໃນ Policy",levelDefault:"ຄ່າເລີ່ມຕົ້ນຂອງ LEVEL",levelFallback:"Job Level",levelHelp:"Permission ທີ່ເປີດຢູ່ນີ້ຈະເປັນ Default ຂອງທຸກ Grade ພາຍໃຕ້ Level ນີ້",saveLevel:"ບັນທຶກ Level",saving:"ກຳລັງບັນທຶກ...",gradeOverride:"GRADE OVERRIDE",gradeFallback:"Job Grade",gradeHelp:"Inherit ໃຊ້ຄ່າຈາກ Level, Grant ເພີ່ມສິດ ແລະ Revoke ເອົາສິດທີ່ Level ໃຫ້ອອກ",saveGrade:"ບັນທຶກ Grade",inherit:"ຮັບຊ່ວງ",grant:"ໃຫ້ສິດ",revoke:"ຖອນສິດ",grantedByGrade:"GRANT ໂດຍ GRADE",revokedByGrade:"REVOKE ໂດຍ GRADE",grantedByLevel:"GRANT ໂດຍ LEVEL",notGranted:"ບໍ່ໄດ້ຮັບຈາກ POLICY",baseRole:"EMPLOYEE Base Role",baseRoleHelp:"ສິດພື້ນຖານຂອງພະນັກງານ",levelStep:"Level Default",levelStepHelp:"Capability ເພີ່ມຕາມ Job Level",gradeStep:"Grade Override",gradeStepHelp:"Grade ປັບສະເພາະ Permission ທີ່ຕ້ອງແຕກຕ່າງ",adminRole:"Admin Role",adminRoleHelp:"ສິດ Tool/Admin ເພີ່ມ ບໍ່ຜູກກັບ Grade",levelSaved:"ບັນທຶກ Default Permission ຂອງ Level ແລ້ວ",gradeSaved:"ບັນທຶກ Grade Override ແລ້ວ",loadError:"ບໍ່ສາມາດໂຫຼດ Level / Grade Permission Policy ໄດ້",levelSaveError:"ບໍ່ສາມາດບັນທຶກ Job Level Permission Policy ໄດ້",gradeSaveError:"ບໍ່ສາມາດບັນທຶກ Job Grade Permission Policy ໄດ້"}
} as const;

export default function OrganizationPermissionPolicyPageClient(){
  const locale=useSuperAdminLocale(); const c=copy[locale];
  const [policy,setPolicy]=useState<OrganizationPermissionPolicy|null>(null); const [selectedLevelId,setSelectedLevelId]=useState<string|null>(null); const [selectedGradeId,setSelectedGradeId]=useState<string|null>(null); const [levelDraft,setLevelDraft]=useState<string[]>([]); const [gradeDraft,setGradeDraft]=useState<Record<string,GradeEffect>>({}); const [loading,setLoading]=useState(true); const [savingLevel,setSavingLevel]=useState(false); const [savingGrade,setSavingGrade]=useState(false); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);
  async function load(signal?:AbortSignal){setLoading(true);setError(null);try{const data=await fetchOrganizationPermissionPolicy(signal);setPolicy(data);setSelectedLevelId(cur=>cur&&data.levels.some(x=>x.id===cur)?cur:data.levels[0]?.id||null);}catch(e){if(signal?.aborted)return;setError(e instanceof Error?e.message:c.loadError);}finally{if(!signal?.aborted)setLoading(false);}}
  useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort();},[]);
  const selectedLevel=useMemo(()=>policy?.levels.find(level=>level.id===selectedLevelId)||null,[policy,selectedLevelId]); const gradesForLevel=useMemo(()=>(policy?.grades||[]).filter(grade=>grade.jobLevelId===selectedLevelId),[policy,selectedLevelId]); const selectedGrade=useMemo(()=>gradesForLevel.find(grade=>grade.id===selectedGradeId)||gradesForLevel[0]||null,[gradesForLevel,selectedGradeId]);
  useEffect(()=>{if(!selectedLevel){setLevelDraft([]);return;}setLevelDraft(selectedLevel.permissionCodes);setSelectedGradeId(cur=>gradesForLevel.some(g=>g.id===cur)?cur:gradesForLevel[0]?.id||null);setNotice(null);},[selectedLevel,gradesForLevel]);
  useEffect(()=>{if(!selectedGrade){setGradeDraft({});return;}const next:Record<string,GradeEffect>={};for(const item of selectedGrade.overrides)next[item.permissionCode]=item.effect;setGradeDraft(next);setNotice(null);},[selectedGrade]);
  function toggleLevel(code:string){setLevelDraft(cur=>cur.includes(code)?cur.filter(x=>x!==code):[...cur,code]);setNotice(null);} function setGradeEffect(code:string,effect:GradeEffect){setGradeDraft(cur=>{const n={...cur};if(effect==="INHERIT")delete n[code];else n[code]=effect;return n;});setNotice(null);}
  async function saveLevel(){if(!selectedLevel)return;setSavingLevel(true);setError(null);setNotice(null);try{const result=await updateJobLevelPermissionPolicy(selectedLevel.id,levelDraft);setPolicy(cur=>cur?{...cur,levels:cur.levels.map(level=>level.id===selectedLevel.id?{...level,permissionCodes:result.permissionCodes}:level)}:cur);setLevelDraft(result.permissionCodes);setNotice(`${c.levelSaved} ${selectedLevel.code}`);}catch(e){setError(e instanceof Error?e.message:c.levelSaveError);}finally{setSavingLevel(false);}}
  async function saveGrade(){if(!selectedGrade)return;setSavingGrade(true);setError(null);setNotice(null);try{const overrides:JobGradePermissionOverride[]=Object.entries(gradeDraft).filter(([,effect])=>effect!=="INHERIT").map(([permissionCode,effect])=>({permissionCode,effect:effect as "GRANT"|"REVOKE"}));const result=await updateJobGradePermissionPolicy(selectedGrade.id,overrides);setPolicy(cur=>cur?{...cur,grades:cur.grades.map(grade=>grade.id===selectedGrade.id?{...grade,overrides:result.overrides}:grade)}:cur);setNotice(`${c.gradeSaved} ${c.grade} ${selectedGrade.gradeNumber}`);}catch(e){setError(e instanceof Error?e.message:c.gradeSaveError);}finally{setSavingGrade(false);}}
  function effectiveFor(code:string){const effect=gradeDraft[code]||"INHERIT";if(effect==="GRANT")return c.grantedByGrade;if(effect==="REVOKE")return c.revokedByGrade;if(levelDraft.includes(code))return c.grantedByLevel;return c.notGranted;}
  return <QBMSAppShell pageTitle={c.pageTitle} pageDescription={c.pageDescription}><div className={styles.page}>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{c.eyebrow}</span><h2>{c.title}</h2><p>{c.intro}</p></div><div className={styles.heroRight}><div className={styles.rules}><span>{c.rule1}</span><span>{c.rule2}</span><span>{c.rule3}</span></div><Link href="/super-admin/roles-permissions" className={styles.backLink}>{c.back}</Link></div></section>
    {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
    <section className={styles.selectorCard}><div><label>{c.jobLevel}</label><select value={selectedLevelId||""} onChange={e=>setSelectedLevelId(e.target.value)} disabled={loading}>{(policy?.levels||[]).map(level=><option key={level.id} value={level.id}>{level.description||level.code} — {level.name}</option>)}</select></div><div><label>{c.jobGrade}</label><select value={selectedGrade?.id||""} onChange={e=>setSelectedGradeId(e.target.value)} disabled={!gradesForLevel.length}>{gradesForLevel.map(grade=><option key={grade.id} value={grade.id}>{c.grade} {grade.gradeNumber} — {grade.name}</option>)}</select></div><div className={styles.summary}><span>{c.policyPermissions}</span><strong>{policy?.permissions.length??"—"}</strong></div></section>
    <section className={styles.policyGrid}><div className={styles.panel}><div className={styles.panelHead}><div><span className={styles.kicker}>{c.levelDefault}</span><h3>{selectedLevel?.description||selectedLevel?.code||c.levelFallback}</h3><p>{c.levelHelp}</p></div><button type="button" className={styles.primaryButton} disabled={!selectedLevel||savingLevel} onClick={saveLevel}>{savingLevel?c.saving:c.saveLevel}</button></div><div className={styles.permissionList}>{(policy?.permissions||[]).map(permission=>{const checked=levelDraft.includes(permission.code);return <button key={permission.code} type="button" className={`${styles.permissionRow} ${checked?styles.levelChecked:""}`} onClick={()=>toggleLevel(permission.code)}><span className={styles.checkbox}>{checked?<QBMSIcon name="check" size={15}/>:null}</span><span className={styles.permissionCopy}><strong>{permission.name}</strong><small>{permission.code}</small><em>{permission.group}</em></span></button>})}</div></div>
      <div className={styles.panel}><div className={styles.panelHead}><div><span className={styles.kicker}>{c.gradeOverride}</span><h3>{selectedGrade?`${c.grade} ${selectedGrade.gradeNumber} — ${selectedGrade.name}`:c.gradeFallback}</h3><p>{c.gradeHelp}</p></div><button type="button" className={styles.primaryButton} disabled={!selectedGrade||savingGrade} onClick={saveGrade}>{savingGrade?c.saving:c.saveGrade}</button></div><div className={styles.gradeList}>{(policy?.permissions||[]).map(permission=>{const effect=gradeDraft[permission.code]||"INHERIT";const effective=effectiveFor(permission.code);return <article key={permission.code} className={styles.gradeRow}><div><strong>{permission.name}</strong><small>{permission.code}</small><span className={`${styles.effective} ${effective.includes("GRANT")?styles.effectiveGrant:effective.includes("REVOKE")?styles.effectiveRevoke:""}`}>{effective}</span></div><div className={styles.segmented}>{(["INHERIT","GRANT","REVOKE"] as GradeEffect[]).map(option=><button type="button" key={option} className={effect===option?styles.activeSegment:""} onClick={()=>setGradeEffect(permission.code,option)}>{option==="INHERIT"?c.inherit:option==="GRANT"?c.grant:c.revoke}</button>)}</div></article>})}</div></div></section>
    <section className={styles.explainer}><div><span className={styles.step}>1</span><strong>{c.baseRole}</strong><p>{c.baseRoleHelp}</p></div><span className={styles.plus}>+</span><div><span className={styles.step}>2</span><strong>{c.levelStep}</strong><p>{c.levelStepHelp}</p></div><span className={styles.arrow}>→</span><div><span className={styles.step}>3</span><strong>{c.gradeStep}</strong><p>{c.gradeStepHelp}</p></div><span className={styles.plus}>+</span><div><span className={styles.step}>4</span><strong>{c.adminRole}</strong><p>{c.adminRoleHelp}</p></div></section>
  </div></QBMSAppShell>;
}
