'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import QBMSAppShell,{QBMSIcon} from '@/components/layout/QBMSAppShell';
import {useI18n} from '@/i18n/useQBMSI18n';
import {assignExistingAsset,completeWithAssets,fetchAssetGate,fetchAssetGates,markNoAssetRequired,quickRegisterAsset,returnAssetAssignment,type AssetGateCase,type AssetGateDetail} from './assetGate.api';
import styles from './AssetGatePage.module.css';

const COPY:any={
 en:{title:'Employee Asset Gate',description:'Complete employee asset handoff before activation.',search:'Search employee, Business Unit or Position...',eyebrow:'HRM / ASSET GATE',hero:'Asset handoff before activation',heroBody:'Assign one or more company assets from the Shared Asset Module, or mark that no asset is required. Completing this gate never activates the employee automatically.',queue:'Asset Gate Queue',pending:'Pending Asset Gate',ready:'Ready for Activation',assigned:'Assigned Assets',available:'Available Assets',register:'Quick Register Asset',gateDecision:'Complete Asset Gate',noAsset:'No Asset Required',complete:'Complete with Assigned Assets',note:'Gate Note',refresh:'Refresh',back:'Employee Master',hrReview:'HR Review',activation:'Activation',noCases:'No Asset Gate cases found.',select:'Select an employee to manage the Asset Gate.',assetCode:'Asset Code',assetName:'Asset Name',assetType:'Asset Type',serial:'Serial Number',assetNotes:'Asset Notes',assignmentNote:'Assignment Note',registerAssign:'Register & Assign',assign:'Assign',return:'Return',none:'—',history:'Asset Gate History',confirmNo:'Mark No Asset Required and complete this gate?',confirmComplete:'Complete Asset Gate with the currently assigned assets?',confirmReturn:'Return this asset to Available?',working:'Saving...',next:'Next Step: Activation',open:'OPEN',done:'COMPLETED'},
 th:{title:'Employee Asset Gate',description:'ตรวจและส่งมอบทรัพย์สินให้พนักงานก่อน Activate',search:'ค้นหาพนักงาน สายธุรกิจ หรือตำแหน่ง...',eyebrow:'HRM / ASSET GATE',hero:'ส่งมอบ Asset ก่อน Activate',heroBody:'มอบหมายทรัพย์สินบริษัทจาก Shared Asset Module ให้พนักงาน หรือระบุว่าไม่ต้องใช้ Asset การจบ Gate นี้จะยังไม่ Activate พนักงานอัตโนมัติ',queue:'คิว Asset Gate',pending:'รอ Asset Gate',ready:'พร้อม Activate',assigned:'Asset ที่มอบหมายแล้ว',available:'Asset ที่พร้อมใช้งาน',register:'เพิ่ม Asset แบบรวดเร็ว',gateDecision:'จบ Asset Gate',noAsset:'ไม่ต้องใช้ Asset',complete:'จบด้วย Asset ที่มอบหมายแล้ว',note:'หมายเหตุ Gate',refresh:'รีเฟรช',back:'Employee Master',hrReview:'HR Review',activation:'Activation',noCases:'ไม่พบรายการ Asset Gate',select:'เลือกพนักงานเพื่อจัดการ Asset Gate',assetCode:'Asset Code',assetName:'ชื่อ Asset',assetType:'ประเภท Asset',serial:'Serial Number',assetNotes:'หมายเหตุ Asset',assignmentNote:'หมายเหตุการมอบหมาย',registerAssign:'เพิ่มและมอบหมาย',assign:'มอบหมาย',return:'คืน Asset',none:'—',history:'ประวัติ Asset Gate',confirmNo:'ยืนยันว่าไม่ต้องใช้ Asset และจบ Gate นี้?',confirmComplete:'ยืนยันจบ Asset Gate ด้วย Asset ที่มอบหมายอยู่?',confirmReturn:'ยืนยันคืน Asset นี้กลับเป็น Available?',working:'กำลังบันทึก...',next:'ขั้นตอนถัดไป: Activation',open:'กำลังดำเนินการ',done:'เสร็จแล้ว'},
 lo:{title:'Employee Asset Gate',description:'ກວດແລະມອບ Asset ກ່ອນ Activate',search:'ຄົ້ນຫາພະນັກງານ, ສາຍທຸລະກິດ ຫຼື ຕຳແໜ່ງ...',eyebrow:'HRM / ASSET GATE',hero:'Asset handoff ກ່ອນ Activate',heroBody:'ມອບ Asset ຂອງບໍລິສັດຈາກ Shared Asset Module ຫຼື ລະບຸວ່າບໍ່ຕ້ອງໃຊ້ Asset. ການປິດ Gate ຈະບໍ່ Activate ພະນັກງານອັດຕະໂນມັດ.',queue:'ຄິວ Asset Gate',pending:'ລໍຖ້າ Asset Gate',ready:'ພ້ອມ Activate',assigned:'Asset ທີ່ມອບແລ້ວ',available:'Asset ທີ່ພ້ອມໃຊ້',register:'Quick Register Asset',gateDecision:'ປິດ Asset Gate',noAsset:'ບໍ່ຕ້ອງໃຊ້ Asset',complete:'ປິດດ້ວຍ Asset ທີ່ມອບແລ້ວ',note:'ໝາຍເຫດ Gate',refresh:'ຣີເຟຣຊ',back:'Employee Master',hrReview:'HR Review',activation:'Activation',noCases:'ບໍ່ພົບ Asset Gate',select:'ເລືອກພະນັກງານເພື່ອຈັດການ Asset Gate',assetCode:'Asset Code',assetName:'Asset Name',assetType:'Asset Type',serial:'Serial Number',assetNotes:'Asset Notes',assignmentNote:'Assignment Note',registerAssign:'Register & Assign',assign:'Assign',return:'Return',none:'—',history:'Asset Gate History',confirmNo:'ຢືນຢັນວ່າບໍ່ຕ້ອງໃຊ້ Asset?',confirmComplete:'ຢືນຢັນປິດ Asset Gate?',confirmReturn:'ຢືນຢັນຄືນ Asset?',working:'ກຳລັງບັນທຶກ...',next:'ຂັ້ນຕໍ່ໄປ: Activation',open:'OPEN',done:'COMPLETED'}
};
function fullName(r:any){const n=[r.first_name,r.last_name].filter(Boolean).join(' ');return r.nickname?`${n} (${r.nickname})`:n}
export default function AssetGatePageClient(){
 const {locale}=useI18n(); const c=COPY[locale]||COPY.en;
 const [rows,setRows]=useState<AssetGateCase[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState<AssetGateDetail|null>(null),[query,setQuery]=useState(''),[assetSearch,setAssetSearch]=useState(''),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');
 const [form,setForm]=useState({assetCode:'',assetName:'',assetType:'Laptop',serialNumber:'',assetNotes:'',assignmentNote:''});
 const loadRows=useCallback(async()=>{setLoading(true);setError('');try{const data=await fetchAssetGates(locale);setRows(data);setSelectedId(cur=>cur&&data.some(r=>String(r.employee_id)===cur)?cur:(data[0]?String(data[0].employee_id):null));}catch(e){setError(e instanceof Error?e.message:'Unable to load Asset Gate.')}finally{setLoading(false)}},[locale]);
 const loadDetail=useCallback(async(id:string)=>{setError('');try{setDetail(await fetchAssetGate(id,locale,assetSearch));}catch(e){setError(e instanceof Error?e.message:'Unable to load Asset Gate detail.')}},[locale,assetSearch]);
 useEffect(()=>{void loadRows()},[loadRows]); useEffect(()=>{if(selectedId)void loadDetail(selectedId);else setDetail(null)},[selectedId,loadDetail]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>[r.employee_code,r.first_name,r.last_name,r.nickname,r.company_email,r.business_unit_name,r.position_name].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))},[rows,query]);
 const counts=useMemo(()=>({open:rows.filter(r=>r.case_status==='HR_APPROVED').length,done:rows.filter(r=>r.case_status==='ASSET_COMPLETED').length}),[rows]);
 async function act(fn:()=>Promise<AssetGateDetail>){setWorking(true);setError('');try{const next=await fn();setDetail(next);await loadRows();setSelectedId(String(next.gate.employee_id));}catch(e){setError(e instanceof Error?e.message:'Unable to save Asset Gate.')}finally{setWorking(false)}}
 async function register(){if(!selectedId)return;await act(()=>quickRegisterAsset(selectedId,form,locale));setForm({assetCode:'',assetName:'',assetType:'Laptop',serialNumber:'',assetNotes:'',assignmentNote:''})}
 return <QBMSAppShell pageTitle={c.title} pageDescription={c.description} searchValue={query} onSearchChange={setQuery} searchPlaceholder={c.search}>
  <div className="qbms-breadcrumb"><Link href="/">Modules & Tools</Link><span>›</span><Link href="/employees">Employee</Link><span>›</span><strong>{c.title}</strong></div>
  <section className="qbms-master-header"><div><div className="qbms-eyebrow">{c.eyebrow}</div><h2>{c.hero}</h2><p>{c.heroBody}</p></div><div className="qbms-master-header-actions"><Link className="qbms-secondary-button" href="/hrm/onboarding-review"><QBMSIcon name="check" size={16}/>{c.hrReview}</Link><Link className="qbms-secondary-button" href="/hrm/activation"><QBMSIcon name="shield" size={16}/>{c.activation}</Link><Link className="qbms-secondary-button" href="/employees"><QBMSIcon name="arrowLeft" size={16}/>{c.back}</Link><button className="qbms-secondary-button" onClick={()=>void loadRows()}><QBMSIcon name="refresh" size={16}/>{c.refresh}</button></div></section>
  <section className="qbms-master-stats"><div className="qbms-stat-card"><span>{c.pending}</span><strong>{counts.open}</strong><small>HR_APPROVED</small></div><div className="qbms-stat-card"><span>{c.ready}</span><strong>{counts.done}</strong><small>ASSET_COMPLETED</small></div></section>
  {error?<section className={styles.error}><strong>!</strong><span>{error}</span></section>:null}
  <section className={styles.workspace}><aside className={styles.queue}><div className={styles.panelHeader}><div><h3>{c.queue}</h3><p>{c.pending}</p></div><span>{filtered.length}</span></div>{loading?<div className={styles.empty}>Loading...</div>:filtered.length?<div className={styles.queueList}>{filtered.map(r=><button key={r.employee_id} onClick={()=>setSelectedId(String(r.employee_id))} className={`${styles.queueItem} ${selectedId===String(r.employee_id)?styles.selected:''}`}><div className={styles.avatar}>{r.first_name?.slice(0,1)?.toUpperCase()||'?'}</div><div className={styles.queueBody}><strong>{fullName(r)}</strong><span>{r.employee_code} · {r.position_name||c.none}</span><small>{r.business_unit_name||c.none}</small></div><em className={r.case_status==='ASSET_COMPLETED'?styles.doneBadge:styles.openBadge}>{r.case_status==='ASSET_COMPLETED'?c.done:c.open}</em></button>)}</div>:<div className={styles.empty}>{c.noCases}</div>}</aside>
  <main className={styles.detail}>{!selectedId?<div className={styles.emptyLarge}>{c.select}</div>:!detail?<div className={styles.emptyLarge}>Loading...</div>:<GateDetail detail={detail} c={c} working={working} note={note} setNote={setNote} form={form} setForm={setForm} assetSearch={assetSearch} setAssetSearch={setAssetSearch} onReload={()=>loadDetail(selectedId)} onRegister={register} onAssign={(assetId:string)=>act(()=>assignExistingAsset(selectedId,assetId,note,locale))} onReturn={(assignmentId:string)=>{if(window.confirm(c.confirmReturn))void act(()=>returnAssetAssignment(selectedId,assignmentId,note,locale))}} onComplete={()=>{if(window.confirm(c.confirmComplete))void act(()=>completeWithAssets(selectedId,note,locale))}} onNoAsset={()=>{if(window.confirm(c.confirmNo))void act(()=>markNoAssetRequired(selectedId,note,locale))}}/>}</main></section>
 </QBMSAppShell>
}
function GateDetail({detail,c,working,note,setNote,form,setForm,assetSearch,setAssetSearch,onReload,onRegister,onAssign,onReturn,onComplete,onNoAsset}:any){const g=detail.gate;const open=g.case_status==='HR_APPROVED';return <div className={styles.stack}>
 <section className={styles.hero}><div><span>{g.employee_code}</span><h2>{fullName(g)}</h2><p>{g.company_email||c.none}</p></div><div className={g.case_status==='ASSET_COMPLETED'?styles.readyStatus:styles.pendingStatus}><strong>{g.case_status==='ASSET_COMPLETED'?c.ready:c.pending}</strong><small>{detail.assignments.length} Asset(s)</small></div></section>
 {g.case_status==='ASSET_COMPLETED'?<section className={styles.success}><QBMSIcon name="check" size={18}/><div><strong>{c.ready}</strong><span>{c.next}</span></div></section>:null}
 <section className={styles.card}><div className={styles.cardTitle}><h3>{c.assigned}</h3><span>{detail.assignments.length}</span></div>{detail.assignments.length?<div className={styles.assetList}>{detail.assignments.map((a:any)=><div key={a.assignment_id} className={styles.assetRow}><div className={styles.assetIcon}><QBMSIcon name="box"/></div><div><strong>{a.asset_name}</strong><span>{a.asset_code} · {a.asset_type}{a.serial_number?` · SN ${a.serial_number}`:''}</span><small>Assigned {new Date(a.assigned_at).toLocaleString()}</small></div>{open?<button disabled={working} onClick={()=>onReturn(a.assignment_id)}>{c.return}</button>:null}</div>)}</div>:<div className={styles.emptyCard}>{c.none}</div>}</section>
 {open?<><section className={styles.card}><div className={styles.cardTitle}><div><h3>{c.available}</h3><p>Shared Asset Module</p></div><div className={styles.assetSearch}><input value={assetSearch} onChange={e=>setAssetSearch(e.target.value)} placeholder="Asset code / name / serial"/><button onClick={onReload}>Search</button></div></div>{detail.available_assets.length?<div className={styles.assetList}>{detail.available_assets.map((a:any)=><div key={a.id} className={styles.assetRow}><div className={styles.assetIcon}><QBMSIcon name="box"/></div><div><strong>{a.asset_name}</strong><span>{a.asset_code} · {a.asset_type}{a.serial_number?` · SN ${a.serial_number}`:''}</span></div><button disabled={working} onClick={()=>onAssign(a.id)}>{c.assign}</button></div>)}</div>:<div className={styles.emptyCard}>{c.none}</div>}</section>
 <section className={styles.card}><div className={styles.cardTitle}><div><h3>{c.register}</h3><p>Creates the record in Shared Asset Module, then assigns it to this employee.</p></div></div><div className={styles.formGrid}>{[['assetCode',c.assetCode],['assetName',c.assetName],['assetType',c.assetType],['serialNumber',c.serial],['assetNotes',c.assetNotes],['assignmentNote',c.assignmentNote]].map(([key,label]:any)=><label key={key}><span>{label}</span><input value={form[key]} onChange={e=>setForm((v:any)=>({...v,[key]:e.target.value}))}/></label>)}</div><div className={styles.cardFooter}><button className={styles.primary} disabled={working||!form.assetCode.trim()||!form.assetName.trim()||!form.assetType.trim()} onClick={onRegister}><QBMSIcon name="box" size={16}/>{working?c.working:c.registerAssign}</button></div></section>
 <section className={styles.decision}><div><h3>{c.gateDecision}</h3><p>Complete only after the required company assets have been handled.</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={c.note}/></div><div className={styles.decisionActions}><button className={styles.noAsset} disabled={working||detail.assignments.length>0} onClick={onNoAsset}>{c.noAsset}</button><button className={styles.complete} disabled={working||detail.assignments.length<1} onClick={onComplete}><QBMSIcon name="check" size={16}/>{c.complete}</button></div></section></>:null}
 <section className={styles.card}><div className={styles.cardTitle}><h3>{c.history}</h3><span>{detail.history.length}</span></div>{detail.history.length?<div className={styles.history}>{detail.history.map((h:any)=><div key={h.id}><span>{h.event_type}</span><div><strong>{h.note||c.none}</strong><small>{new Date(h.created_at).toLocaleString()}</small></div></div>)}</div>:<div className={styles.emptyCard}>{c.none}</div>}</section>
 </div>}
